cluster.name: es-cluster_klima

node.name: es00_klima
node.master: false
node.data: false
node.rack: minion04

path.logs: /opt/elasticsearch/logs

network.host: 10.2.36.219

discovery.zen.ping.unicast.hosts: ["10.2.148.5", "10.2.139.3", "10.2.36.219"]
